colors = {
    "FRAME_COLOR": "#31353D",
    "SEARCH_BUTTON_COLOR": "#6B7482",
    "SEARCH_BAR_COLOR": "white",
    "PUSH_BUTTON_TEXT_COLOR": "white",
    "PUSH_BUTTON_COLOR": "#262829",
    "PUSH_BUTTON_PRESSED_COLOR": "#111314",
    "TITLEBAR_BUTTON_COLOR": "#31353D",
}
