# Some of this file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
from pathlib import Path
from tkinter import *

from bulk.gui_utils import Center
from utils.authUtils import *


def login():
    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path("assets")

    def authenticate(*args):
        try:
            users = userTable()
            users.loadCredentials('data/users.json')
            username = key.get()
            password = value.get()
            if users.authenticate(username, password):
                window.destroy()
                print("SUCCESSFUL AUTH")
            else:
                canvas.itemconfig(not_auth_msg, state='normal')

        except ValueError:
            pass

    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)

    window = Tk()
    window.overrideredirect(True)

    window.geometry("606x392")
    Center(window)

    window.configure(bg="#31353D")
    window.attributes('-topmost', True)
    window.update()

    bg_color = "#31353D"

    canvas = Canvas(
        window,
        bg=bg_color,
        height=392,
        width=606,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )

    canvas.place(x=0, y=0)
    canvas.create_text(
        216.0,
        231.0,
        anchor="nw",
        text="Passkey",
        fill="#FFFFFF",
        font=("Inter", 12 * -1)
    )

    canvas.create_text(
        216.0,
        181.0,
        anchor="nw",
        text="Employee ID",
        fill="#FFFFFF",
        font=("Inter Regular", 12 * -1)
    )

    not_auth_msg = canvas.create_text(
        230.0,
        275.0,
        anchor="nw",
        text="credentials not recognized",
        fill="#FF0D00",
        font=("Inter", 12 * -1),
        state='hidden'
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("login_entry.png"))
    entry_bg_1 = canvas.create_image(
        303.5,
        212.5,
        image=entry_image_1
    )

    key = StringVar()
    value = StringVar()

    username = Entry(
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0,
        textvariable=key
    )
    username.bind('<Return>', authenticate)
    username.place(
        x=227.5,
        y=203.0,
        width=152.0,
        height=17.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        303.5,
        262.5,
        image=entry_image_2
    )
    password = Entry(
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0,
        textvariable=value,
        show='●'
    )
    password.bind('<Return>', authenticate)
    password.place(
        x=227.5,
        y=253.0,
        width=152.0,
        height=17.0
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("authButton.png"))
    button_1 = Button(
        image=button_image_1,
        bg="#2E3031",
        activebackground="#181A1B",
        borderwidth=0,
        highlightthickness=0,
        command=authenticate,
        relief="flat"
    )
    button_1.place(
        x=260.0,
        y=300.0,
        width=87.0,
        height=18.0
    )

    image_image_1 = PhotoImage(
        file=relative_to_assets("F-SEAlogo.png"))
    image_1 = canvas.create_image(
        303.0,
        125.0,
        image=image_image_1
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("closeButton.png"))
    button_2 = Button(
        image=button_image_2,
        bg="#31353D",
        activebackground="#31353D",
        borderwidth=0,
        highlightthickness=0,
        command=window.destroy,
        relief="flat"
    )
    button_2.place(
        x=575.0,
        y=6.0,
        width=24.0,
        height=24.0
    )
    window.resizable(False, False)
    window.mainloop()
