# Form implementation generated from reading ui file '.\fsea-database.-options.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        MainWindow.resize(577, 361)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(550, 345))
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonSpacerFrame = QtWidgets.QFrame(self.centralwidget)
        self.buttonSpacerFrame.setEnabled(True)
        self.buttonSpacerFrame.setMinimumSize(QtCore.QSize(118, 41))
        self.buttonSpacerFrame.setStyleSheet(" background-color: #31353d;")
        self.buttonSpacerFrame.setObjectName("buttonSpacerFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.buttonSpacerFrame)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.buttonSpacerFrame, 2, 0, 2, 1)
        self.buttonFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonFrame.sizePolicy().hasHeightForWidth())
        self.buttonFrame.setSizePolicy(sizePolicy)
        self.buttonFrame.setStyleSheet(" background-color: #31353d;")
        self.buttonFrame.setObjectName("buttonFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.buttonFrame)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.verticalLayout_4.setContentsMargins(9, 0, 9, 9)
        self.verticalLayout_4.setSpacing(9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.employeedbButton = QtWidgets.QPushButton(self.buttonFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.employeedbButton.sizePolicy().hasHeightForWidth())
        self.employeedbButton.setSizePolicy(sizePolicy)
        self.employeedbButton.setMinimumSize(QtCore.QSize(100, 65))
        self.employeedbButton.setStyleSheet("QPushButton { color: white;\n"
"                                    background-color: #262829;\n"
"                                    border: none; }\n"
"                                    QPushButton::pressed { background-color: #111314; }")
        self.employeedbButton.setObjectName("employeedbButton")
        self.verticalLayout_4.addWidget(self.employeedbButton)
        self.specimendbButton = QtWidgets.QPushButton(self.buttonFrame)
        self.specimendbButton.setMinimumSize(QtCore.QSize(100, 65))
        self.specimendbButton.setStyleSheet("QPushButton { color: white;\n"
"                                    background-color: #262829;\n"
"                                    border: none; }\n"
"                                    QPushButton::pressed { background-color: #111314; }")
        self.specimendbButton.setObjectName("specimendbButton")
        self.verticalLayout_4.addWidget(self.specimendbButton)
        self.missiondbButton = QtWidgets.QPushButton(self.buttonFrame)
        self.missiondbButton.setMinimumSize(QtCore.QSize(100, 65))
        self.missiondbButton.setStyleSheet("QPushButton { color: white;\n"
"                                    background-color: #262829;\n"
"                                    border: none; }\n"
"                                    QPushButton::pressed { background-color: #111314; }")
        self.missiondbButton.setObjectName("missiondbButton")
        self.verticalLayout_4.addWidget(self.missiondbButton)
        self.departmentdbButton = QtWidgets.QPushButton(self.buttonFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departmentdbButton.sizePolicy().hasHeightForWidth())
        self.departmentdbButton.setSizePolicy(sizePolicy)
        self.departmentdbButton.setMinimumSize(QtCore.QSize(100, 65))
        self.departmentdbButton.setStyleSheet("QPushButton { color: white;\n"
"                                    background-color: #262829;\n"
"                                    border: none; }\n"
"                                    QPushButton::pressed { background-color: #111314; }")
        self.departmentdbButton.setObjectName("departmentdbButton")
        self.verticalLayout_4.addWidget(self.departmentdbButton)
        self.gridLayout_2.addWidget(self.buttonFrame, 1, 0, 1, 1)
        self.titlebar = QtWidgets.QFrame(self.centralwidget)
        self.titlebar.setMinimumSize(QtCore.QSize(550, 30))
        self.titlebar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.titlebar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.titlebar.setStyleSheet("background-color: #31353D;\n"
"color: white;")
        self.titlebar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.titlebar.setObjectName("titlebar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titlebar)
        self.horizontalLayout.setContentsMargins(15, 5, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title = QtWidgets.QLabel(self.titlebar)
        self.title.setObjectName("title")
        self.horizontalLayout.addWidget(self.title)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.minimizeButton = QtWidgets.QPushButton(self.titlebar)
        self.minimizeButton.setMinimumSize(QtCore.QSize(18, 18))
        self.minimizeButton.setMaximumSize(QtCore.QSize(18, 18))
        self.minimizeButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.minimizeButton.setStyleSheet("QPushButton { color: white;\n"
"                                    background-color: #31353D;\n"
"                                    border: none; }\n"
"                                    QPushButton::pressed { background-color: #111314; }")
        self.minimizeButton.setText("")
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout.addWidget(self.minimizeButton)
        self.restoreButton = QtWidgets.QPushButton(self.titlebar)
        self.restoreButton.setMinimumSize(QtCore.QSize(18, 18))
        self.restoreButton.setMaximumSize(QtCore.QSize(18, 18))
        self.restoreButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.restoreButton.setStyleSheet("QPushButton { color: white;\n"
"                                    background-color: #31353D;\n"
"                                    border: none; }\n"
"                                    QPushButton::pressed { background-color: #111314; }")
        self.restoreButton.setText("")
        self.restoreButton.setObjectName("restoreButton")
        self.horizontalLayout.addWidget(self.restoreButton)
        self.exitButton = QtWidgets.QPushButton(self.titlebar)
        self.exitButton.setMinimumSize(QtCore.QSize(18, 18))
        self.exitButton.setMaximumSize(QtCore.QSize(18, 18))
        self.exitButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.exitButton.setStyleSheet("QPushButton { color: white;\n"
"                                    background-color: #31353D;\n"
"                                    border: none; }\n"
"                                    QPushButton::pressed { background-color: #111314; }")
        self.exitButton.setText("")
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton)
        self.gridLayout_2.addWidget(self.titlebar, 0, 0, 1, 2)
        self.searchFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchFrame.sizePolicy().hasHeightForWidth())
        self.searchFrame.setSizePolicy(sizePolicy)
        self.searchFrame.setMinimumSize(QtCore.QSize(432, 317))
        self.searchFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.searchFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.searchFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.searchFrame.setObjectName("searchFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.searchFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.searchButton = QtWidgets.QPushButton(self.searchFrame)
        self.searchButton.setMinimumSize(QtCore.QSize(50, 20))
        self.searchButton.setStyleSheet("QPushButton { color: white;\n"
"                                    background-color: rgb(107, 116, 130);\n"
"                                    border: none; }\n"
"                                    QPushButton::pressed { background-color: #262829; }")
        self.searchButton.setObjectName("searchButton")
        self.gridLayout.addWidget(self.searchButton, 0, 1, 1, 1)
        self.searchBar = QtWidgets.QLineEdit(self.searchFrame)
        self.searchBar.setObjectName("searchBar")
        self.gridLayout.addWidget(self.searchBar, 0, 0, 1, 1)

        self.scrollArea = QtWidgets.QScrollArea(self.searchFrame)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 439, 285))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.textBrowser = QtWidgets.QTextBrowser(self.verticalFrame)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 75))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 75))
        self.textBrowser.setObjectName("textBrowser")

        self.verticalLayout_2.addWidget(self.textBrowser)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.verticalFrame)
        self.textBrowser_4.setMinimumSize(QtCore.QSize(0, 75))
        self.textBrowser_4.setMaximumSize(QtCore.QSize(16777215, 75))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.verticalLayout_2.addWidget(self.textBrowser_4)
        self.verticalLayout_3.addWidget(self.verticalFrame, 0, QtCore.Qt.AlignmentFlag.AlignTop)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.searchFrame, 1, 1, 3, 1)
        self.footer = QtWidgets.QFrame(self.centralwidget)
        self.footer.setGeometry(QtCore.QRect(538, 325, 16, 20))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 20))
        self.footer.setStyleSheet("background-color: white;")
        self.footer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.footer.setObjectName("footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sizeGrip = QtWidgets.QFrame(self.footer)
        self.sizeGrip.setMaximumSize(QtCore.QSize(20, 20))
        self.sizeGrip.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.sizeGrip.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sizeGrip.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sizeGrip.setObjectName("sizeGrip")
        self.horizontalLayout_2.addWidget(self.sizeGrip)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "F-SEA Database"))
        self.employeedbButton.setText(_translate("MainWindow", "Employees"))
        self.specimendbButton.setText(_translate("MainWindow", "Specimens"))
        self.missiondbButton.setText(_translate("MainWindow", "Missions"))
        self.departmentdbButton.setText(_translate("MainWindow", "Departments"))
        self.title.setText(_translate("MainWindow", "F-SEA Database"))
        self.searchButton.setText(_translate("MainWindow", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
